[config]
schemaVersion = "0.0.1"

[package]
namespace = "helskog"
name = "VTemplate"
versionNumber = "0.1.0"
description = "descriptionString"
websiteUrl = "https://github.com/helskog/VTemplate"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"
deca-VampireCommandFramework = "0.9.0"

[build]
icon = "./logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/net6.0/VTemplate.dll"
target = "./VTemplate.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["Server", "Mods", "Oakveil Update"]